version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - pytest

  post_build:
    commands:
      - echo "Build complete!"

