version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y wget
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo apt install -y libxss1 libappindicator1 libindicator7 xvfb
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo apt --fix-broken install
      - sudo apt-get install -f   # This command will attempt to fix any dependency issues
      - sudo apt-get clean
      - sudo apt-get update
      - sudo apt-get install -y fonts-liberation libasound2 libatk-bridge2.0-0 libatspi2.0-0 libgbm1 libgtk-3-0 libu2f-udev libvulkan1 libxkbcommon0 xdg-utils
      - sudo dpkg -i google-chrome-stable_current_amd64.deb
      - apt-get update && apt-get install -y xvfb
      - dpkg -i google-chrome-stable_current_amd64.deb
      - apt-get install -y -f
  build:
    commands:
      - google-chrome-stable --version
