version: 0.2

phases:
  install:
    commands:
      - pip install pytest
      - pip install selenium
      - pip install webdriver-manager
      - pip install requests
      - pip install --upgrade webdriver_manager
      - sudo apt-get update -y
      - sudo apt-get install -y wget
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt-get install -y -f ./google-chrome-stable_current_amd64.deb


  build:
    commands:
      - google-chrome-stable --version
      - which google-chrome
      - python itero.py
      #- cd ptests
      #- pytest

