version: 0.2

phases:
  install:
    commands:
      - pip install pytest
      - pip install selenium
      - pip install webdriver-manager
      - apt-get update
      - apt-get install -y wget
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt-get install -y -f ./google-chrome-stable_current_amd64.deb
      - sudo dpkg -i google-chrome-stable_current_amd64.deb
      - sudo apt-get -y install --no-install-recommends unzip
      - wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - sudo mv chromedriver /usr/local/bin/
      - sudo chmod +x /usr/local/bin/chromedriver
  build:
    commands:
      - google-chrome-stable --version
      - which google-chrome
      - chrome
      - cd ptests
      - pytest
