version: 0.2

phases:
  install:
    commands:
    
      - pip install pytest
      - pip install -r requirements.txt
      - sudo apt update
      - sudo apt install -y libxss1 libappindicator1 libindicator7 xvfb
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo apt --fix-broken install
      - sudo apt-get install -f   # This command will attempt to fix any dependency issues
      - sudo apt-get clean
      - sudo dpkg -i google-chrome-stable_current_amd64.deb





  build:
    commands:
      - cd ptests
      - pytest  -m stories

