version: 0.2

phases:
  install:
    commands:
      - sudo yum install python3-pip -y
      - pip3 install pytest
      - pip3 install selenium
      - pip3 install webdriver-manager
      - pip3 install requests
      - yum update -y
      - yum install -y wget
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - yum localinstall -y google-chrome-stable_current_x86_64.rpm

  build:
    commands:
      - google-chrome-stable --version
      - which google-chrome
      - cd ptests
      - pytest

