version: 0.2

phases:
  install:
    runtime-versions:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - pytest  -m stories -v -o log_cli=true --log-cli-level=INFO

  post_build:
    commands:
      - echo "Build complete!"

