version: 0.2

phases:
  install:
    commands:
    
      - pip install pytest
      - pip install -r requirements.txt
      - sudo apt update

  build:
    commands:
      - cd ptests
      - pytest  -m stories

